# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

#...
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allday', models.BooleanField(default=False, verbose_name='Dia inteiro')),
                ('title', models.CharField(max_length=128, verbose_name='evento')),
                ('start', models.DateTimeField(verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='fim')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='solicitado em')),
                ('authorized', models.BooleanField(default=False, verbose_name='autorizado')),
                ('editable', models.BooleanField(default=True, verbose_name='Editavel')),
                ('color', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black'), ('yellow', 'yellow')], default='blue', max_length=15, verbose_name='cor')),
                ('backgroundColor', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black'), ('yellow', 'yellow')], default='blue', max_length=15, verbose_name='Cor de Fundo')),
                ('overlap', models.BooleanField(default=True, verbose_name='Descartavel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reservas',
                'ordering': ('-start',),
                'verbose_name': 'reserva',
            },
        ),
    ]
