# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateField(verbose_name='fim'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateField(verbose_name='inicio'),
        ),
    ]
