# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20161113_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='color',
            field=models.CharField(default=1, max_length=8, verbose_name='cor'),
            preserve_default=False,
        ),
    ]
