# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_booking_feriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(related_name='item_participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
