# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='backgroundColor',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='overlap',
            field=models.BooleanField(default=True, verbose_name='Sobrepor'),
        ),
    ]
