# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='color',
            field=models.CharField(max_length=15, verbose_name='cor'),
        ),
    ]
