# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20161126_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allday',
            field=models.BooleanField(default=False, verbose_name='Dia inteiro'),
        ),
        migrations.AddField(
            model_name='booking',
            name='backgroundColor',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black')], default='blue', max_length=15, verbose_name='Cor de Fundo'),
        ),
        migrations.AddField(
            model_name='booking',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='Editavel'),
        ),
    ]
