# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20161128_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='backgroundColor',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black'), ('yellow', 'yellow')], default='blue', max_length=15, verbose_name='Cor de Fundo'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black'), ('yellow', 'yellow')], default='blue', max_length=15, verbose_name='cor'),
        ),
    ]
