# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20161128_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='overlap',
            field=models.BooleanField(default=True, verbose_name='Descartavel'),
        ),
    ]
