# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Opcional: Imagem do usuário'),
        ),
    ]
